### ISSUE TITLE
I can run in python script choosing doge.py

### ISSUE THREAD

**Issue by cryptosaver** [Pymmdrza/AttackAIO_Crypto#6]
I can run in python script choosing doge.py but don't know how to run all.
How to run 00BatchAttack.bat as the main,py in python?

**Comment by Pymmdrza** [comment]
> I can run in python script choosing doge.py but don't know how to run all. How to run 00BatchAttack.bat as the main,py in python?

Update File `doge.py` can follow [here](https://github.com/Pymmdrza/AttackAIO_Crypto/edit/mainx/README.md#dogecoin-hunting-and-check-mnemonics-words-convert-private-key-and-check-value-from-dogecoin-address-wallet-) for more detail and download update file doge.py from [here](https://github.com/Pymmdrza/AttackAIO_Crypto/blob/mainx/doge.py 'Dogecoin Hunting Script Power Attack AIO V2')

### Screen From 'doge.py' Dogecoin AIO Attack:
![Dogecoin AIO Attack for Hunting and Crack Private Key](https://raw.githubusercontent.com/Pymmdrza/AttackAIO_Crypto/mainx/media/dogescreen_aio.png 'Dogecoin AIO Attack for Hunting and Crack Private Key')
