### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mrjvadi** [Pymmdrza/AttackAIO_Crypto#7]
Hi.
I have an error. When I give him words, he makes some mistakes
https://prnt.sc/SBdSDdeHkUc_
words : password, 123456,

**Comment by Pymmdrza** [comment]
> Hi. I have an error. When I give him words, he makes some mistakes https://prnt.sc/SBdSDdeHkUc_ words : password, 123456,

Check Now : and Use From New File : [ethereum.py](https://github.com/Pymmdrza/AttackAIO_Crypto/blob/mainx/ethereum.py)

for running this file needed install this package :

`pip install requests-html`
`pip install hdwallet`
`pip install ecdsa`
